"""
Django settings for Inner_Sparc_Portal project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env", override=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-ibkk6slw%jlf6%g*clu)x0p-x1flul6r62qa2rxa10lobnm$@e')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "True").strip().lower() in ("1", "true", "yes", "on")

ONBOARDING_DEV_UNLOCK_ALL = False  # Keep strict onboarding locks and sequential validation enabled

ALLOWED_HOSTS = ['inner-sparc-portal-main.onrender.com', 'localhost', '127.0.0.1']

# Path to Firebase service account key JSON.
# Download from: Firebase Console -> Project Settings -> Service Accounts
#                -> Generate new private key
# Save the file as 'firebase-service-account.json' in the project root.
FIREBASE_ADMIN_CREDENTIALS = BASE_DIR / "firebase-service-account.json"

# Server-side Google OAuth (authorization-code flow)
GOOGLE_OAUTH_CLIENT_ID = os.getenv(
    "GOOGLE_OAUTH_CLIENT_ID",
    "913007976233-lf6s6al248tonu3v2rk5v66ltggfft5e.apps.googleusercontent.com",
)
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv(
    "GOOGLE_OAUTH_CLIENT_SECRET",
    "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",
)
GOOGLE_OAUTH_REDIRECT_URI = os.getenv("GOOGLE_OAUTH_REDIRECT_URI", "")

# Groq AI chatbot settings (server-side only).
GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_MODEL = os.getenv("GROQ_MODEL", "llama-3.3-70b-versatile")
GROQ_MAX_TOKENS = int(os.getenv("GROQ_MAX_TOKENS", "700"))
GROQ_MODEL_FALLBACKS = [
    GROQ_MODEL,
    "llama-3.1-8b-instant",
    "llama-3.3-70b-versatile",
    "mixtral-8x7b-32768",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'app.middleware.PortalSessionTimeoutMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Inner_Sparc_Portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'app' / 'template' / 'html'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Inner_Sparc_Portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
PROJECT_STATIC_DIR = BASE_DIR / 'static'
STATICFILES_DIRS = [PROJECT_STATIC_DIR] if PROJECT_STATIC_DIR.exists() else []
STATIC_ROOT = BASE_DIR / 'staticfiles'
if DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Public base URL for absolute assets in outbound emails.
# Example: https://portal.innersparc.com
EMAIL_ASSET_BASE_URL = (os.getenv("EMAIL_ASSET_BASE_URL", "https://example.com") or "https://example.com").strip().rstrip("/")
if EMAIL_ASSET_BASE_URL and not EMAIL_ASSET_BASE_URL.lower().startswith("https://"):
    EMAIL_ASSET_BASE_URL = "https://" + EMAIL_ASSET_BASE_URL.lstrip("/")

# Email settings
# Provider selection via EMAIL_PROVIDER:
# - auto (default): picks first configured provider in this order: postmark -> resend -> brevo -> smtp
# - postmark requires POSTMARK_SERVER_TOKEN
# - resend requires RESEND_API_KEY
# - brevo requires BREVO_API_KEY
# - smtp requires EMAIL_HOST_USER + EMAIL_HOST_PASSWORD
# Falls back to console backend only when no delivery provider is configured.
EMAIL_PROVIDER = os.getenv("EMAIL_PROVIDER", "auto").strip().lower()
POSTMARK_SERVER_TOKEN = os.getenv("POSTMARK_SERVER_TOKEN", "")
RESEND_API_KEY = os.getenv("RESEND_API_KEY", "")
BREVO_API_KEY = os.getenv("BREVO_API_KEY", "")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@innersparc.local")
EMAIL_AUDIT_BCC = os.getenv("EMAIL_AUDIT_BCC", "").strip()
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "20"))
ANYMAIL = {}
EMAIL_CONFIGURATION_ERROR = ""

selected_email_provider = EMAIL_PROVIDER or "auto"
if selected_email_provider == "auto":
    if POSTMARK_SERVER_TOKEN:
        selected_email_provider = "postmark"
    elif RESEND_API_KEY:
        selected_email_provider = "resend"
    elif BREVO_API_KEY:
        selected_email_provider = "brevo"
    elif EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
        selected_email_provider = "smtp"
    else:
        selected_email_provider = "console"

EMAIL_BACKEND = os.getenv("EMAIL_BACKEND", "").strip()

if selected_email_provider == "postmark":
    if POSTMARK_SERVER_TOKEN:
        EMAIL_BACKEND = EMAIL_BACKEND or "anymail.backends.postmark.EmailBackend"
        ANYMAIL["POSTMARK_SERVER_TOKEN"] = POSTMARK_SERVER_TOKEN
    else:
        EMAIL_CONFIGURATION_ERROR = "EMAIL_PROVIDER=postmark requires POSTMARK_SERVER_TOKEN."
elif selected_email_provider == "resend":
    if RESEND_API_KEY:
        EMAIL_BACKEND = EMAIL_BACKEND or "anymail.backends.resend.EmailBackend"
        ANYMAIL["RESEND_API_KEY"] = RESEND_API_KEY
    else:
        EMAIL_CONFIGURATION_ERROR = "EMAIL_PROVIDER=resend requires RESEND_API_KEY."
elif selected_email_provider == "brevo":
    if BREVO_API_KEY:
        EMAIL_BACKEND = EMAIL_BACKEND or "anymail.backends.brevo.EmailBackend"
        ANYMAIL["BREVO_API_KEY"] = BREVO_API_KEY
    else:
        EMAIL_CONFIGURATION_ERROR = "EMAIL_PROVIDER=brevo requires BREVO_API_KEY."
elif selected_email_provider == "smtp":
    if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
        EMAIL_BACKEND = EMAIL_BACKEND or "django.core.mail.backends.smtp.EmailBackend"
        EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
        EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
        EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "true").strip().lower() in ("1", "true", "yes", "on")
        EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "false").strip().lower() in ("1", "true", "yes", "on")
    else:
        EMAIL_CONFIGURATION_ERROR = "EMAIL_PROVIDER=smtp requires EMAIL_HOST_USER and EMAIL_HOST_PASSWORD."
elif selected_email_provider != "console":
    EMAIL_CONFIGURATION_ERROR = f"Unsupported EMAIL_PROVIDER value: {selected_email_provider}"

if not EMAIL_BACKEND:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_NON_DELIVERY_BACKENDS = (
    "django.core.mail.backends.console.EmailBackend",
    "django.core.mail.backends.dummy.EmailBackend",
    "django.core.mail.backends.filebased.EmailBackend",
)

# Celery + Redis settings
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TASK_DEFAULT_QUEUE = os.getenv("CELERY_TASK_DEFAULT_QUEUE", "default")
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = int(os.getenv("CELERY_TASK_TIME_LIMIT", "120"))
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv("CELERY_TASK_SOFT_TIME_LIMIT", "90"))

# Windows-friendly Celery defaults: prefork is unstable on local Windows workers.
if os.name == "nt":
    CELERY_WORKER_POOL = os.getenv("CELERY_WORKER_POOL", "solo")
    CELERY_WORKER_CONCURRENCY = int(os.getenv("CELERY_WORKER_CONCURRENCY", "1"))

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
