# Generated by Django 5.1.2 on 2026-03-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_onboardingprofile_application_review_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprofile',
            name='application_status',
        ),
        migrations.RemoveField(
            model_name='onboardingprofile',
            name='rejection_reason',
        ),
        migrations.RemoveField(
            model_name='onboardingprofile',
            name='reviewed_at',
        ),
    ]
