# Generated by Django 5.1.2 on 2026-03-27 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_userprofile_admin_role_and_review_audit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboardingprofile',
            name='application_review_decision',
        ),
        migrations.RemoveField(
            model_name='onboardingprofile',
            name='application_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='onboardingprofile',
            name='application_reviewer_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='admin_role',
        ),
    ]
