# Generated by Django 5.1.2 on 2026-07-16 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_onboardingprofile_module_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginsecuritystate',
            name='user',
        ),
        migrations.DeleteModel(
            name='SecuritySettings',
        ),
        migrations.DeleteModel(
            name='LoginSecurityState',
        ),
    ]
