from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('sign-in/', views.SignInPageView.as_view(), name='sign_in'),
    path('sign-up/', views.SignUpPageView.as_view(), name='sign_up'),
    path('forgot-password/', views.ForgotPasswordPageView.as_view(), name='forgot_password'),
    path('template-beta/', views.TemplateBetaPageView.as_view(), name='template_beta'),
    path('template2/', views.Template2PageView.as_view(), name='template2'),
    path('portal-admin/accounts/', views.portal_admin_accounts, name='portal_admin_accounts'),
    path('portal-admin/superusers/', views.portal_admin_superusers, name='portal_admin_superusers'),
    path('portal-admin/superusers/role/', views.portal_admin_superuser_role_update, name='portal_admin_superuser_role_update'),
    path('portal-admin/superusers/password/', views.portal_admin_superuser_password_update, name='portal_admin_superuser_password_update'),
    path('portal-admin/notifications/', views.portal_admin_notifications, name='portal_admin_notifications'),
    path('portal-admin/security-settings/', views.portal_admin_security_settings, name='portal_admin_security_settings'),
    path('portal-admin/security-settings/update/', views.portal_admin_security_settings_update, name='portal_admin_security_settings_update'),
    path('portal-admin/user-files/<int:user_id>/', views.admin_user_files, name='admin_user_files'),
    path('portal-admin/user-progress/<int:user_id>/', views.admin_user_progress, name='admin_user_progress'),
    path('portal-admin/approve-application/', views.admin_approve_application, name='admin_approve_application'),
    path('portal-admin/reject-application/', views.admin_reject_application, name='admin_reject_application'),
    path('portal-admin/send-training-reminder/', views.admin_send_training_reminder, name='admin_send_training_reminder'),
    path('portal-onboarding/complete/', views.portal_onboarding_complete, name='portal_onboarding_complete'),
    path('portal-onboarding/completion-email-status/', views.portal_onboarding_completion_email_status, name='portal_onboarding_completion_email_status'),
    path('portal-onboarding/progress/', views.portal_onboarding_progress, name='portal_onboarding_progress'),
    path('portal-onboarding/video-proxy/', views.portal_training_video_proxy, name='portal_training_video_proxy'),
    path('portal-onboarding/comments/', views.comments_list, name='comments_list'),
    path('portal-onboarding/comments/create/', views.comments_create, name='comments_create'),
    path('portal-onboarding/comments/<int:comment_id>/edit/', views.comments_edit, name='comments_edit'),
    path('portal-onboarding/comments/<int:comment_id>/delete/', views.comments_delete, name='comments_delete'),
    path('portal-onboarding/profile-data/', views.portal_onboarding_profile_data, name='portal_onboarding_profile_data'),
    path('portal-onboarding/profile-identity/save/', views.portal_onboarding_profile_identity_save, name='portal_onboarding_profile_identity_save'),
    path('portal-onboarding/agent-documents/save/', views.portal_onboarding_agent_documents_save, name='portal_onboarding_agent_documents_save'),
    path('portal-onboarding/avatar/upload/', views.portal_onboarding_avatar_upload, name='portal_onboarding_avatar_upload'),
    path('portal-onboarding/step-complete/', views.portal_onboarding_step_complete, name='portal_onboarding_step_complete'),
    path('login/', views.portal_login, name='login'),
    path('signup/', views.portal_signup, name='signup'),
    path('portal-auth/signup/', views.portal_signup, name='portal_signup'),
    path('portal-auth/login/', views.portal_login, name='portal_login'),
    path('portal-auth/status/', views.portal_auth_status, name='portal_auth_status'),
    path('portal-auth/logout/', views.portal_logout, name='portal_logout'),
    path('portal-account/update/', views.portal_account_update, name='portal_account_update'),
    path('portal-auth/firebase-login/', views.portal_firebase_login, name='portal_firebase_login'),
    path('portal-auth/google/start/', views.portal_google_start, name='portal_google_start'),
    path('portal-auth/google/callback/', views.portal_google_callback, name='portal_google_callback'),
    path('portal-ai/chat/', views.portal_ai_chat, name='portal_ai_chat'),
]
